---
- vsphere_guest:
    vcenter_hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    guest: "{{ vm_name }}"
    state: "{{ vm_state }}"
    vm_extra_config:
      vcpu.hotadd: yes
      mem.hotadd:  yes
      notes: "{{ vm_notes }}"
    vm_disk: "{{ vm_disk }}"
    vm_nic: "{{ vm_nic }}"
    vm_hardware:
      memory_mb: "{{ vm_mem }}"
      num_cpus: "{{ vm_cpu }}"
      osid: "{{ vm_osid }}"
      scsi: paravirtual
    esxi:
      datacenter: "{{ datacenter }}"
      hostname: "{{ target_esxi }}"
  register: deploy
  delegate_to: localhost
